### PR TITLE
Rework affiliate

### PR DESCRIPTION
**Pull request by mchigit**
This PR is hard to test because I had to create multiple new accounts to link new affiliates. I did some testing but wanted to get more testers to try it out. 

New Affiliate flow:
- Nothing is changed if the user manually clicks the `Affiliate` header
- If user comes from a link with a sponsor address, we will show a platinum card instead of share my link. If user clicks "next", then we move to next state and will show both link form and share my link div. User can click "previous" to go back to the previous state

Initial state: 
image

Next state: 
image

### CODE REVIEW

**Comment by ryanprice** [comment]
It's complaining in AppHeader line 342

      if (this.sponsorAddress.toLowerCase() === this.coinbase.toLowerCase()) {
        return false;
      }

not sure why ?

**Comment by mchigit** [comment]
> It's complaining in AppHeader line 342
> 
> ```
>   if (this.sponsorAddress.toLowerCase() === this.coinbase.toLowerCase()) {
>     return false;
>   }
> ```
> 
> not sure why ?

had a bug. Should be fixed now

**Comment by ryanprice** [comment]
Bug is fixed.
Can we move the word Next 
down to bottom right and rename to Skip

**Comment by mchigit** [comment]
> Bug is fixed.
> Can we move the word Next
> down to bottom right and rename to Skip

Do we still want `Previous` in that case?

**Review by ryanprice — APPROVED** [review]
Looks good

**Pull request merged**
