### PR TITLE
rework market

### PR DESCRIPTION
**Pull request by mchigit**
make market look cleaner and mobile responsive.

### CODE REVIEW

**Review by jjjhill — CHANGES_REQUESTED** [review]
- The 1inch exchange logo is white on white background making it invisible
- The images are pretty small on mobile, maybe setting a fixed height and including them in the top row or something
image

**Review by ryanprice — COMMENTED** [review]
Can we make the unclicked button(tab) on the right coloured maybe light grey or something that makes it look like a button or that its clickable ?

Screenshot 2021-04-11 7 49 14 PM

**Comment by mchigit** [comment]
> * The 1inch exchange logo is white on white background making it invisible
> * The images are pretty small on mobile, maybe setting a fixed height and including them in the top row or something
>   image

It doesn't look too good if I inline the image with the title. Since we have a lot of space on this page anyway, I made it above the title:
image

**Review by ryanprice — APPROVED** [review]
Let's go with this

**Review by jjjhill — APPROVED** [review]

**Pull request merged**
