### PR TITLE
Refactor toast message into util function and use toast with spinner

### PR DESCRIPTION
**Pull request by mchigit**
Changes:
- Refactored triggering toast into a util function, which will trigger pending, success, rejected toasts correspondingly
- Modified `CryptContent` to use toasts instead of spinner and showing transaction status

### CODE REVIEW

**Review by jjjhill — APPROVED** [review]
beauty

**Comment by ryanprice** [comment]
Looks good !
I get 2 toasts popping up on confirmation of the sacrifice that say the same thing, Balance is updated.  Is that the expected behavior ?

**Comment by mchigit** [comment]
> Looks good !
> I get 2 toasts popping up on confirmation of the sacrifice that say the same thing, Balance is updated. Is that the expected behavior ?

Hmm so I think this is because of the `currentEvent` function being fired twice. Before all it did was to set the transaction status, which we decided to use toast instead. I was thinking I can get this refactor PR in so it doesn't block anyone else's work, and I will focus tonight on figuring out why that function runs twice whenever the balance gets updated

**Review by ryanprice — APPROVED** [review]
Works great for reject and approve.

**Pull request merged**
