### PR TITLE
add sponsor modal

### PR DESCRIPTION
**Pull request by mchigit**
A lot of changes are formatting changes. 

Change:
- Added sponsor link on header if connected with Metamask
- Able to copy own sponsor link as `url?sponsor=0x3u...`
- If never linked, there will be an input with link button to add a sponsor
- Once linked, should not be able to link again
- If goes to an url with `?sponsor=...` present, will open the modal on loaded with input filled in (if connected)

### CODE REVIEW

**Review by ryanprice — COMMENTED** [review]
Looks great and works great for pasting the link and detecting no wallet address and actually connecting a sponsor to wallet and earning the platinum card

I have a constant "You are already linked to sponsor message" even when I didnt have a sponsor.  I was in a wallet that was linked.. and then changed wallet and pasted the affiliate link and it still displayed the connected message. 

image

**Comment by ryanprice** [comment]
Can we change the label up top from "Your Sponsor Link" to "Your Affiliate Link", I may fine tune some of the wording after merge, no worries : )

**Comment by mchigit** [comment]
> Looks great and works great for pasting the link and detecting no wallet address and actually connecting a sponsor to wallet and earning the platinum card
> 
> I have a constant "You are already linked to sponsor message" even when I didnt have a sponsor. I was in a wallet that was linked.. and then changed wallet and pasted the affiliate link and it still displayed the connected message.
> 
> image

Can you give it another try? I also fixed the header text

**Review by jjjhill — APPROVED** [review]
Niceeeu

**Review by ryanprice — APPROVED** [review]
Wicked, go for it, looks and works great

**Pull request merged**
