### PR TITLE
show spinner when sacrificing in progress

### PR DESCRIPTION
**Pull request by mchigit**
image

### CODE REVIEW

**Comment by ryanprice** [comment]
Works great, should we disable the clicked sacrifice button while its pending confirmation ?

**Comment by mchigit** [comment]
> Works great, should we disable the clicked sacrifice button while its pending confirmation ?

Yep. I will add that

**Review by ryanprice — APPROVED** [review]
Excellent

**Comment by nlamb4** [comment]
Sorry for the later response. It would look cleaner if the spinner stopped when the sacrifice is cancelled. When you close the metamask dialog box after clicking sacrifice, there's a popup that says "Transaction rejected" but the sacrifice spinner keeps going. Then you can click sacrifice on another card and have 2+ spinners going at the same time, and cancel the 2nd one and start a 3rd, etc etc. Thoughts?

**Comment by mchigit** [comment]
> Sorry for the later response. It would look cleaner if the spinner stopped when the sacrifice is cancelled. When you close the metamask dialog box after clicking sacrifice, there's a popup that says "Transaction rejected" but the sacrifice spinner keeps going. Then you can click sacrifice on another card and have 2+ spinners going at the same time, and cancel the 2nd one and start a 3rd, etc etc. Thoughts?

I can't actually reproduce this case. When I run my code locally, the spinner disappears after the transaction is cancelled. Did you just click reject on metamask?

**Comment by nlamb4** [comment]
Yeah, it was happening when I clicked reject and also when I clicked the X on the metamask popup. I was just able to reproduce it but it seems like it sometimes happens and sometimes doesn't, and I don't know why. It's probably not too big of a deal.

**Pull request merged**
